### ISSUE TITLE
Question regarding prometheus.yml

### ISSUE THREAD

**Issue by siavash9000** [bvis/docker-prometheus-swarm#13]
Hello,
would be nice if you could explain how the load balancing of docker swarm is considered. As far as I understand yet, the scraping of prometheus will be routed to some cadvisor or nodeexport instance without any guarantees. How do you get data from all nodes at each scrape interval? How are the datapoint distinguished from each other?
Thank you very much and best regards,
Siavash

**Comment by bvis** [comment]
Hi,

Sorry for late answer, I've been in holidays some days.

In the configuration file you can see the discovery is done using the name `tasks.SERVICE_NAME` instead of the service name directly. For example:
```
- job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080
```
What does this mean? That Prometheus will obtain each task address instead of the VIP that is exposed by the service. This can be checked easily with `nslookup` or similar tools. For example:
```
/prometheus # nslookup tasks.cadvisor
Server:    127.0.0.11
Address 1: 127.0.0.11

Name:      tasks.cadvisor
Address 1: 10.0.2.11 monitoring_cadvisor.x8r85pceclcu3v65103cw69xb.78iqi86zy1gryiqt3fesfp87i.monitoring
Address 2: 10.0.2.13 ce3e0c4ccb2b.monitoring
Address 3: 10.0.2.7 monitoring_cadvisor.uyk276apwnl50sm48t1ef8xbc.u8oyhj1pfw2q2vhozyktt5ah3.monitoring
Address 4: 10.0.2.12 monitoring_cadvisor.1l5y7fe6xsr03wmgb4grvfpoq.ryoqg5dlzexfoo8htlgdursp1.monitoring
Address 5: 10.0.2.10 monitoring_cadvisor.v456k351g1a6cpjlt6bx3roek.yqv7g4mzazhs4pfqwx2xd1syr.monitoring
Address 6: 10.0.2.14 monitoring_cadvisor.78hopxq0d74j4wm9yn3iz8b1u.o90i0tbbhn47wzhkm71fz5wpx.monitoring
```
Instead of the VIP of the cadvisor service which is obtained with
```
/prometheus # nslookup cadvisor
Server:    127.0.0.11
Address 1: 127.0.0.11

Name:      cadvisor
Address 1: 10.0.2.5 ip-10-0-2-5.eu-west-1.compute.internal
```
As the `cadvisor` service has been deployed as a global service, we can be sure that each task is in a different node, and when you add new nodes to the cluster it will have its own cadvisor task, which will be discovered immediately by Prometheus.

These addresses do not change while the task is running, then you can be sure that the data coming from one task is from the same node.

I hope this explanation is clear enough, if you have any doubt feel free to contact me at any moment.

**Comment by bvis** [comment]
I'll close this issue, feel free to open it if you have more questions.
