### ISSUE TITLE
Instance Name

### ISSUE THREAD

**Issue by caiohasouza** [bvis/docker-prometheus-swarm#15]
Hello!

It's possible show in "instance" fileld the hostname of server instead the IP:Port?

Regards

**Comment by bvis** [comment]
Hi, I think it's not possible when using DNS based service discovery. I wrote a more detailed answer here: https://medium.com/@basi/hi-pierre-8dcb260f982b

On other hand in the Grafana Dashboard I created for consuming this data you can see the hostnames: https://grafana.com/dashboards/609

I hope it helps.

**Comment by caiohasouza** [comment]
Hi @bvis 

Right, in the your first commentary i need create some "cron" to update the file "/etc/prometheus/prometheus.sd.json"? I don't understand how it will be updated and how i use the hostname in relabel process, would have you some example?

And about your second commentary yes, i'm using your Dashboard and it is perfect, good work! but if i restart my node-exporter container i lost the old data, do you understand?

Regards

**Comment by bvis** [comment]
Well, you should not create any cron to update the file, you should watch for swarm events in the docker manager API and react to them accordingly redefining the `prometheus.sd.json` file.

Prometheus will take care of detect that the file has changed and update its internal discovery configuration.

As I said in my medium comment there are projects that try to do something like this, partially, on other hand. One possible approach could be modify one of them to add the new option. I checked 
@vfarcic [Docker Flow Swarm Listener](https://github.com/vfarcic/docker-flow-swarm-listener) but it needs many changes because now it just obtains services and it should obtain services, tasks and nodes for generate a file based service discovery, lots of changes. But it could be integrated very well with his [Docker Flow Swarm Monitor](https://github.com/vfarcic/docker-flow-monitor) project.

If I had enough time I could try do implement some of these changes myself, but unfortunately my current situation does not allow me to do it. 😅

**Comment by vfarcic** [comment]
If you can tell me which information you'd need from [DFSL](https://github.com/vfarcic/docker-flow-swarm-listener), I'd be more than happy to add it. The same goes for [DFM](https://github.com/vfarcic/docker-flow-monitor). Please open an issue in [https://github.com/vfarcic/docker-flow-swarm-listener/issues](https://github.com/vfarcic/docker-flow-swarm-listener/issues) or [https://github.com/vfarcic/docker-flow-monitor/issues](https://github.com/vfarcic/docker-flow-monitor/issues) and I'll do my best to work on it ASAP. PRs are more than welcome.

**Comment by caiohasouza** [comment]
So currently we don't have solution "ready" for this problem, right?

**Comment by caiohasouza** [comment]
@bvis 

I thought in a "workaround", see:

- In template "$instance", change "Refresh" inside "Query Options" to "On Time Range Change";

In this way your dashboard will be "group" all InstanceID on a Tag with hostname, so i will can see all history data.

What do you think?

Regards

**Comment by bvis** [comment]
@xdexter It's something easy to try, does it "fix" the problem of "losing" the old data?

@vfarcic Here you are: https://github.com/vfarcic/docker-flow-monitor/issues/10
I've added some rude examples just for give a clue about a possible implementation.

**Comment by caiohasouza** [comment]
Hi @bvis 

Yes, because in this way all instance:port will be groupped in a tag, see:

![grafana01](https://user-images.githubusercontent.com/10849509/31715948-a910df4e-b3e4-11e7-9eff-8823f2706f45.png)

Do you understand?

**Comment by bvis** [comment]
Done!

**Comment by caiohasouza** [comment]
Hi @bvis,

Sorry, i don't understand, did you done something?

Regards

**Comment by bvis** [comment]
I've updated the dashboard with your suggestion. ;)

**Comment by caiohasouza** [comment]
Ah Ok, thank you!
